import type { NextPage } from "next";
import Head from "next/head";
import FilterTypes from "../components/filterTypes";
import { Flex, Text } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex bg="#F7F8FD" p="5vh 10vw" justify="space-between">
        <Flex direction="column" w="24vw">
          <FilterTypes />
        </Flex>
        <Flex direction="column"> second </Flex>
      </Flex>
    </div>
  );
};

export default Home;
