import { embed } from "@aws/dynamodb-data-mapper";
import {
  attribute,
  table,
  autoGeneratedHashKey,
} from "@aws/dynamodb-data-mapper-annotations";
import { Comment } from "./comment";

@table("github_suggestions")
export class Suggestion {
  @autoGeneratedHashKey()
  suggestionID!: string;

  @attribute()
  title!: string;

  @attribute()
  description!: string;

  @attribute()
  category!: Array<string>;

  @attribute()
  repo!: string;

  @attribute()
  author!: string;

  @attribute()
  upvotes!: number;

  @attribute({ memberType: embed(Comment) })
  comments!: Array<Comment>;
}
